# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser (https://goreleaser.com).
#
# HOMEBREW CORE: This is a placeholder formula.
# For actual installation, users should tap the repository:
#   brew tap erickcortez/tuipr
#   brew install tuipr

class Tuipr < Formula
  desc "A keyboard-driven Pull Request Lifecycle Manager for your terminal"
  homepage "https://github.com/erickcortez/tuipr"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/erickcortez/tuipr/releases/download/v#{version}/tuipr_#{version}_Darwin_x86_64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_DARWIN_AMD64"
    end

    if Hardware::CPU.arm?
      url "https://github.com/erickcortez/tuipr/releases/download/v#{version}/tuipr_#{version}_Darwin_arm64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_DARWIN_ARM64"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/erickcortez/tuipr/releases/download/v#{version}/tuipr_#{version}_Linux_x86_64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_LINUX_AMD64"
    end
  end

  def install
    bin.install "tuipr"
  end

  test do
    assert_match "tuipr", shell_output("#{bin}/tuipr --help 2>&1", 1)
  end
end
